### ISSUE TITLE
symbol.c:1150:3: warning: this ‘if’ clause does not guard

### ISSUE THREAD

**Issue by dcb314** [crosstool-ng/crosstool-ng#1000]
Source code is

                if (stack->sym == last_sym)
                        fprintf(stderr, "%s:%d:error: recursive dependency detected!\n",
                                prop->file->name, prop->lineno);
                        fprintf(stderr, "For a resolution refer to Documentation/kbuild/kconfig-language.txt\n");
                        fprintf(stderr, "subsection \"Kconfig recursive dependency limitations\"\n");

Maybe better code

                if (stack->sym == last_sym)
                {
                        fprintf(stderr, "%s:%d:error: recursive dependency detected!\n",
                                prop->file->name, prop->lineno);
                        fprintf(stderr, "For a resolution refer to Documentation/kbuild/kconfig-language.txt\n");
                        fprintf(stderr, "subsection \"Kconfig recursive dependency limitations\"\n");
                }

**Comment by cpackham** [comment]
This was fixed upstream in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e3b03bf29

Do we regularly sync the kbuild/kconfig code?

**Comment by cpackham** [comment]
Answering my own question looks like the last update was from linux 4.15 which isn't that old but does have this bug. I'll submit a PR to cherry-pick the fix I quoted above.

One issue with updating to the latest kconfig is that I know it's added a dependency on the build host having flex/bison but that may not be a concern since crosstool-ng already requires those. Might need to get the CI situation sorted before doing a wholesale update.
