### ISSUE TITLE
How to modify and recompile just glibc after a full compilation?

### ISSUE THREAD

**Issue by cirosantilli** [crosstool-ng/crosstool-ng#1033]
Continuing my quest to use this to develop glibc, now I want to modify glibc and rebuild and use it easily.

I was trying it to use `EXPERIMENTAL` and `<pkg>_SRC_CUSTOM` https://github.com/crosstool-ng/crosstool-ng/issues/1024 and `CT_DEBUG_CT_SAVE_STEPS` but `./ct-ng libc` failed.

Then I tried a clean build without `<pkg>_SRC_CUSTOM`, and it still failed, am I doing something wrong?

ctng a6580b8 on Ubuntu 18.04 host:

```
export CT_PREFIX="$(pwd)/.build/install"
./ct-ng x86_64-unknown-linux-gnu
```

then in `menuconfig`, only set `CT_DEBUG_CT_SAVE_STEPS=y`, then build:

```
env -u LD_LIBRARY_PATH time ./ct-ng build -j`nproc`
```

works fine.

But now if I try to rebuild just libc which I obtained from `./ct-ng list-steps`

```
env -u LD_LIBRARY_PATH time ./ct-ng libc -j`nproc`
```

then it fails with:

```
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20180926.090329                                           
[INFO ]  Building environment variables
[WARN ]  Directory '/home/ciro/src' does not exist.
[WARN ]  Will not save downloaded tarballs to local storage.
[EXTRA]  Preparing working directories
[ERROR]                        
[ERROR]  >>                                             
[ERROR]  >>  Build failed in step '(top-level)'         
[ERROR]  >>                                         
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@374]       
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@308]
[ERROR]  >>                                   
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>                                
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:  
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>                 
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:                                             
[ERROR]  >>      http://crosstool-ng.github.io/support/              
[ERROR]                   
[ERROR]  (elapsed: 0:01.24)                                                                                                    
[00:01] / /mnt/sda3/git/crosstool-ng/ct-ng:232: recipe for target 'build' failed
```

I'm suspecting this has to do with the fact that some of the directories generated by Buildroot are readonly for some reason, which is another thing that was annoying me since I need to `sudo` or `chmod` when I want to remove.

I suspect this because `build.log` contains:

```
[DEBUG]  ==> Executing:  'touch' '/mnt/sda3/git/crosstool-ng/.build/install/x86_64-unknown-linux-gnu/foo'
[DEBUG]  touch: cannot touch '/mnt/sda3/git/crosstool-ng/.build/install/x86_64-unknown-linux-gnu/foo': Permission denied
```
Full config and build log: https://gist.github.com/cirosantilli/d74bd607e4cfddd433945c8398eaeed1

I can imagine that this step alone is not enough for a decent libc rebuild given the complex list of steps involving `libc` in `list-steps`, but I expect that at least it shouldn't end in error either.

**Comment by stilor** [comment]
First, don't pass `-jX` to ct-ng. It doesn't have the desired effect. While probably harmless on the commands you showed above (since they just invoke a single shell script to do the work anyway), it may result in weird failures for certain others (e.g. `ct-ng build-all` where it would attempt to unpack sources for multiple packages concurrently). Instead, use `PARALLEL_JOBS` option in the configuration - or override it with `ct-ng build.X` or `ct-ng <any-command> CT_JOBS=X`.

Second, I am not sure configuring the installation directory to reside within the temporary build directory is a good idea: it will work until you decide to `ct-ng clean`, for obvious reasons :)

That said, the failure you see is a bug in ct-ng: it first tries to check the case-sensitivity of the filesystem where the installation directory is; to do so, it creates a temporary file inside the installation path. And only afterwards, with an ironic comment that "the installation path may have been changed to read-only", does a `chmod -R +w` on that path.

I'll fix this tonight.

**Comment by stilor** [comment]
> I can imagine that this step alone is not enough for a decent libc rebuild

It should be sufficient to rebuild the glibc. Note that different libcs may do the actual build at different stages; e.g. `avr-libc` builds itself during the `libc_post_cc` step. I am not sure if it is actually needed - but haven't got to change it.

**Comment by cirosantilli** [comment]
@stilor thank you! I confirm that the fix works as you mentioned.
