### ISSUE TITLE
armhf-unknown-linux-musleabi build fail on x86 linux host

### ISSUE THREAD

**Issue by tomkcook** [crosstool-ng/crosstool-ng#1131]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
```
~/crosstool $ ct-ng version
This is crosstool-NG version crosstool-ng-1.23.0

Copyright (C) 2008  Yann E. MORIN <yann.morin.1998@free.fr>
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
```

The host is an Alpine 3.8 docker container running on top of Ubuntu 18.04.

Using the attached .config file, I'm trying to build an `armhf-unknown-linux-musleabi` toolchain.  This fails while building musl, I think because the host type is set incorrectly.  The relevant bit of build.log is shown below and the full file is attached.  It shows musl's `configure` is being run with both host and target set to `armhf-unknown-linux-musleabi` where I think the host should be `x86_64-build_px-linux-gnu-gcc`.

I will try with the `HEAD` version of crosstool and report back today.

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/2831477/config.txt)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2831479/build.log)

**Comment by stilor** [comment]
No, the arguments to configure are fine. Run `./configure --help` in MUSL if you want to check. The error reported in the build.log comes from the compiler - which is apparently, misconfigured in case of `armv8-*-musleabi` triplet. 

This issue seems to be fixed in newer GCC - 8.3.0 no longer produces these bogus "target CPU does not support ARM mode" errors. However, it also fails to compile MUSL:
```
[ERROR]      /home/avn/work/ctng/crosstool-ng/.build/arm-unknown-linux-musleabi/src/musl/src/thread/arm/atomics.s:59: Error: invalid constant (1) after fixup
[ERROR]      /home/avn/work/ctng/crosstool-ng/.build/arm-unknown-linux-musleabi/src/musl/src/thread/arm/atomics.s:74: Error: invalid constant (1) after fixup
```
If you want this fixed, report this to musl maintainers and (assuming the assembly code is correct - I haven't verified that) to GCC lists.
