### ISSUE TITLE
Feature request: build redistributable tarballs

### ISSUE THREAD

**Issue by ali1234** [crosstool-ng/crosstool-ng#1262]
It would be nice if there was an option to make redistributable tarballs of the built toolchain, similar to what Linaro ABE does. For example: https://releases.linaro.org/components/toolchain/binaries/7.4-2019.02/arm-linux-gnueabihf/

I did a small proof-of-concept: https://github.com/ali1234/crosstool-ng/commit/e9cb71e5946bb7172cd3cd8d4590a31138f5f53a

This uses a similar approach to ABE - rsync to copy the toolchain into a directory named after the pkgversion, then tar it, then checksum it (ABE uses md5 but I used sha256).

If you are interested I would like to implement this properly, but there are some details that need to be worked out:

1. What should the variables be called and what should the default values be?
2. Which tarballs should be provided? ABE produces toolchain, sysroot, and runtime. I am not sure how the last two map to ct-ng, so I only did the toolchain.
3. It would be useful to also copy source tarballs to the redist output. Currently ct-ng has one dir for source tarballs and it can have unneeded ones in it.
4. How to make it so that "make clean" etc still works?
5. Should this be a whole new build step?

**Comment by cpackham** [comment]
At $dayjob we'd make use of this kind of feature. Currently we manually tar up the resulting toolchain so we can copy the result between containers.
1. Naming things is hard. Defaulting to off is sensible for the first cut of this feature. We can change the default later if necessary. Others might have an opinion on the destination, but personally I'd go with directory `ct-ng build` was invoked.
2. ct-ng is really just the toolchain so there's nothing for the other two
3. I'd say no (or not without an option to omit them). The ct-ng configuration should allow you to recreate the toolchain. 
4. We don't really clean up the output toolchain with `ct-ng clean` so maybe do nothing. Alternatively if it does end up under the .build directory it will get cleaned up from there.
5. To me it kind of feels wrong to have a step after "finish". But maybe that means just renaming the current "finish"

**Comment by ali1234** [comment]
All sounds reasonable, thanks.

Re 3. it would not put the source into the binary tarball, rather it would make another tarball for sources, or just copy the originals into the output directory (or maybe a subdir of it).

My goal is to distribute a toolchain, and the output of this code should ideally be everything required to do that while complying with the licenses.

**Comment by cpackham** [comment]
> My goal is to distribute a toolchain, and the output of this code should ideally be everything required to do that while complying with the licenses.

That sounds a little like what buildroot do with `make legal-info`

**Comment by ali1234** [comment]
I had a look at what buildroot does and it is quite involved.

There doesn't seem to be a way to easily get a list of all the sources ct-ng uses for the current build as each one is calculated inside its respective build script.

The easiest thing to do is probably to do a clean build and then take the whole sources directory. Its location can already be customized so I won't implement anything extra for this.

**Comment by nolange** [comment]
You know you can remap the directory name with tar? No need to rsync.

Also, is the tool chain relocatable? The prefix path is embedded in multiple places, like ld scripts. So you would need to unpack it in the very same directory.
(at work I am packaging the ct-ng toolchain in a Debian archive, and put it into an apt repository. Easy to install/update/remove)

**Comment by ali1234** [comment]
I know about `tar --transform` but it is surprisingly difficult to get it right due to the use of regex. I went with what ABE does for the first version. Is there a better way to do it with tar?

The toolchain does seem to be relocatable. I've built kernel, qt, and gstreamer with it (including cross compiling gobject-introspection with the ldd wrapper) and I've also tried out many other people's toolchains that aren't relocatable, and I didn't run into any of the usual problems with ct-ng output.

**Comment by nolange** [comment]
Id start with something like this:

```bash
CT_PREFIX_DIR=/opt/ct-ng-build
DATESTR=$(date -I)
NAME=hugotc-${DATESTR}
OUTDIR=/tmp
XZ_OPT=-9 tar -C"${CT_PREFIX_DIR}" -cJf ${OUTDIR}/${NAME}.tar.xz --format=ustar --mtime=${DATESTR} --sort=name --numeric-owner --owner=0 --group=0 --transform='s,^.,'"${NAME}", .
```

Also, just because you dont run into issues, doesnt mean there arent any. I would not know for ex. what happens to the paths in `lib/ldscripts`, might be that you are picking up files from your host installation. some ~7 years ago I tried building a crosstoolchain in a staging directory (ie. installing the files not in their final place) and totally failed, and every toolchain builder including `ct-ng` still lacks that functionality.
those paths unfortunately do matter in some rather subtile ways.

I nowadays just use docker to build in eg. the `/opt`directory, gave up hope on getting a staged build done ;)

**Comment by ali1234** [comment]
Better tell Linaro because they have been distributing relocatable binary toolchains for years. :)

**Comment by ali1234** [comment]
I've pushed a change to make it use `--transform`.

`s,^.,'"${NAME}",` isn't a suitable transform because it will destroy every symlink in the archive.

The best I could come up with is `flags=rh;s,^\.,${NAME},` but I am not convinced this is free of corner cases either.

Something like `flags=rh;s,^(\.)(/|$),out\2,x` may be more robust but I can't think of a case where it would be necessary. Either way it is definitely a lot harder to understand.

**Comment by nolange** [comment]
I did not know transform affects symlinks, now I gonna need to fixup some scripts.

From the manpage you can use a (IMHO) simpler syntax: `s,^.,${NAME},S`.

tar will add a directory `.` and the rest as`./*`, so strictly speaking you would need to replace both (while ensuring you dont replace names like `.config`).
I came up with this solution: `--transform "s,^\./\.,${NAME},S"  ./.`, which is probably as clean as it gets.

Id also recommend picking up the rest of the flags from my previous message, otherwise you could end up with files that are owned by wrong/noexisting users/groups or archives that cant be extracted by some tar implementations (think of using an alpine/busybox container for CI builds).

PS. your rsync approach would have removed hardlink's AFAIK.

**Comment by ali1234** [comment]
Works for me. I'll add it all and open a pull request. I don't see any reason to reset the mtime on every file though.

**Comment by ali1234** [comment]
Setting the format to ustar didn't work:

    tar: toolchain-raspbian-buster-0-2-g62cd2c5-arm-linux-gnueabihf/arm-linux-gnueabihf/sysroot/usr/bin/getconf: link name is too long; not dumped

**Comment by nolange** [comment]
The mtime (and sort) stuff is primary to get the same archive bit for bit if you rebuild, but there is no infrastructure in ct-ng yet so its not important (many compilers/buildsystems support the env variable `SOURCE_DATE_EPOCH` for fixing timestamps).
I don't have much use for timestamps otherwise.

**Comment by abrodkin** [comment]
As I mentioned here https://github.com/crosstool-ng/crosstool-ng/pull/1269#issuecomment-564918183 this attempt to use `--sort` makes this very useful feature unusable on CentOS 7 and probably some other older but still used distros where tar is of version below 1.28.

So maybe just drop sorting given we're not going to have identical binaries from rebuild to rebuild?
