### ISSUE TITLE
Question: can I use crosstool-ng to build a toolchain to create debian-8 binaries?

### ISSUE THREAD

**Issue by janwilmans** [crosstool-ng/crosstool-ng#1467]
I'm looking for a way to build Jessie (debian 8) x64 binaries on a Buster (debian 10) x64 machine, is this something that crosstool-ng could be used for? 

basically, its cross-compiling from one glibc-environment to another, but the same architecture. (x86)

**Comment by cpackham** [comment]
In short no. Crosstool-ng is for generating a toolchain to compile binaries
that will run on a different cpu architecture.

It sounds like your case would be better served by using a debian-jessie
docker container.

**Comment by janwilmans** [comment]
I want to use GCC-10, which is not available on debian 8 (understandbly) so a docker container won't help me. Why is targeting a different x86 toolchain not possible? Is there a longer answer?

**Comment by cpackham** [comment]
You could use the `x86_64-unknown-linux-gnu` sample as a starting point.

To produce an application that runs on debian 8 you'll need to match the libc version (or link statically), which might get interesting. I guess it's possible if you can get all the dependencies for the toolchain and your application lined up.

**Comment by RudolfRendier** [comment]
I have a similar to goal because I'd like to create binaries for Slackware 14.2 x86 (glibc 2.23) from Slackware x64.
And I've managed to create a working toolchain with gcc 8.3.0 (and glibc 2.23) that produces binaries that run on x86.
I'm still a bit wary because it's recommended to use gcc and glibc of a similar age, so I need to do some more tests. It looks promising though.

I started with i686-ubuntu16.04-linux-gnu because 16.04 uses the same glibc version, so that was a good starting point.
I do link everything but libstdc++ and glibc statically.
