### ISSUE TITLE
Downloads are forbidden

### ISSUE THREAD

**Issue by cmpunches** [crosstool-ng/crosstool-ng#1482]
CTNG Version: 1.24.0
Host OS: Debian Buster
Config Used: https://paste.silogroup.org/ninuveceqa.ini
build.log:  https://paste.silogroup.org/edihifapon

Hello,

I have used the `x86_64-unknown-linux-gnu` sample config, and have noticed a couple of things that I could use clarification on to make sure I'm doing this right, and if I am, whether this is an issue in configuration or is a bug (I wouldn't know yet, the configuration on this tool is very complex).  So, I'll bring it to your attention and see what you think.  There are two issues.

First, and least importantly, I've noticed that taking the sample config and running menuconfig against it will add quite a bit more to the config file and even undo some changes previously made to it.  Recommendation on how to handle these files would be well received.  Currently the plan is to just copy the modified config file back to where it's staged from when I get one working.

Second, and more importantly, I've noticed in this sample config that the option to select download agent is forced to "none", and the option to allow downloads is locked down to disallow those downloads.  The exact path in menuconfig is "Paths and misc options  -> Download agent" and "Paths and misc options -> Forbid Downloads". 

This is a screenshot of what I'm actually seeing: https://imgur.com/iyUs8xe.png

It just won't allow the option to download.

As to what I'm "really" trying to do, if that helps, I just want to create a statically linked x64 cross-compiler toolchain (for host, build, and target) for use in the cross-compilation of a linux sysroot.  We plan on adding menus to select different targets later.

Thanks in advance and I hope to see more great things from this project.

**Comment by cpackham** [comment]
The `.confg` is the fully expanded configuration so all options are present there. The samples are the minified config so only the things that aren't defaults are present. You can minify a `.config` with `ct-ng savedefconfig` generally that's what I'd suggest saving if you want re-create the same toolchain later.

I think you've ended up with `CT_DOWNLOAD_AGENT_NONE` because neither wget nor curl were detected when ct-ng was built. This leads to `CT_FORBID_DOWNLOAD` being selected and the problem you see. To fix that you'll need to install the required dependencies  (see [here](https://github.com/crosstool-ng/crosstool-ng/blob/77d75eb2adb06d65a10c5b0fd39e2bd3aee5b8a2/testing/docker/ubuntu18.04/Dockerfile#L7)) and rebuild ct-ng.

**Comment by cmpunches** [comment]
@cpackham That took care of it.  Thanks!

Where do I donate to this project?
