### ISSUE TITLE
Linking error compiling mips-unknown-linux-uclibc: cannot find -lsource-highlight

### ISSUE THREAD

**Issue by danshick** [crosstool-ng/crosstool-ng#1487]
- crosstool-NG version : git master latest, commit hash: 77d75eb2
- Host distro and version: Arch Linux x86_64 (rolling release, up to date)
- Host kernel version: Linux 5.11.11-arch1-1 x86_64 GNU/Linux
- [.config](https://github.com/crosstool-ng/crosstool-ng/files/6306624/config.txt)
- [build.log.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/6306631/build.log.tar.gz)

Most relevant part of build.log:
```
[ALL  ]    /usr/bin/ld: gdbsupport/gdb-dlfcn.o: in function `gdb_dlopen(char const*)':
[ALL  ]    /home/dws/mips/.build/mips-unknown-linux-uclibc/src/gdb/gdb/gdbsupport/gdb-dlfcn.c:65: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
[ALL  ]    /usr/bin/ld: cannot find -lsource-highlight
[ERROR]    collect2: error: ld returned 1 exit status
[ERROR]    make[3]: *** [Makefile:1908: gdb] Error 1
[ALL  ]    make[3]: Leaving directory '/home/dws/mips/.build/mips-unknown-linux-uclibc/build/build-gdb-cross/gdb'
[ERROR]    make[2]: *** [Makefile:9231: all-gdb] Error 2
[ALL  ]    make[2]: Leaving directory '/home/dws/mips/.build/mips-unknown-linux-uclibc/build/build-gdb-cross'
[ERROR]    make[1]: *** [Makefile:853: all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/dws/mips/.build/mips-unknown-linux-uclibc/build/build-gdb-cross'
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gdb_backend[scripts/build/debug/300-gdb.sh@282]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@59]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@695]
```

**Comment by cpackham** [comment]
Hmm. I tried reproducing this locally (using an arch container) it got past cross-gdb but failed for other reasons.

One thing I notice in my build.log is that it hasn't got `-lsource-highlight -L/usr/lib64 -lboost_regex` when linking. Looking at the configure output I see I have `checking for the source-highlight library... no` while you have `checking for the source-highlight library... yes` so that's likely the difference.

I think the various `-L<dir>` have probably messed up finding the source-highlight lib. Not sure what the correct fix is but uninstalling the source-highlight package is probably a workaround.

**Comment by QBos07** [comment]
@cpackham you need to install `extra/source-highlight`

**Comment by QBos07** [comment]
Had the same problem 2 hours of build for nothing:(

**Comment by danshick** [comment]
@QBos07 thanks for the tip.
