### ISSUE TITLE
Support for OpenRISC (Question)

### ISSUE THREAD

**Issue by TallAllie** [crosstool-ng/crosstool-ng#1554]
Hi!

I'm happily using the latest `crosstool-NG` (version 1.24.0) to create a variety of toolchains.

(This is a QUESTION, not an ISSUE...)

`gcc` currently supports [OpenRISC](https://gcc.gnu.org/onlinedocs/gcc/OpenRISC-Options.html).

I see a checkin to crosstool-NG's `contrib` back in 2008(!) to support an OpenRISC/or32/or1k/or1200 TARGET.  Throughout the codebase, I see vestiges of this support.  However, it is not a current TARGET option in `menuconfig`.

Am I just 10 years(!) too late, or is this somehow possible?

Thanks!

**Comment by cpackham** [comment]
I'm not aware of any particular reason not to support openrisc (which I take it is different to riscv). If binutils and gcc support it the only reason we don't have it is because no-one has submitted a PR. The stuff in contrib looks to be out of date so it's probably of little use (we should probably drop it).

If you're interested in adding support for openrisc please go ahead. You could take a look at some of the other architectures in `config/arch/` and `scripts/build/arch`to get a feel for what is needed.

**Comment by cpackham** [comment]
Just out of my own curiosity I gave it a go https://github.com/crosstool-ng/crosstool-ng/pull/1558

I've compile tested the elf and uclibc toolchain but as I have nothing to try it out on I haven't attempted to use it.

**Comment by TallAllie** [comment]
Outstanding!  Let me pull your work, see if I can reproduce it.  I'll then run it on the design that we have here.

I doubt that I'll be as quick as you though!  :-)

**Comment by cpackham** [comment]
Nothing happening on this. Closing for now. We can always re-open if someone re-surfaces looking for openrisc.
