### ISSUE TITLE
Error happened in: CT_DoExecLog[scripts/functions@376]

### ISSUE THREAD

**Issue by liuyibox** [crosstool-ng/crosstool-ng#1580]
- Report crosstool-NG version
This is crosstool-NG version 1.24.0.413_358945f

Copyright (C) 2008  Yann E. MORIN <yann.morin.1998@free.fr>
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

- Report host OS and its version
Linux, Ubuntu 20.04

- Attach `.config` (unless the issue is not related to any configuration)
https://github.com/NVIDIA/DCGM/blob/master/dcgmbuild/x86_64.config

- Attach `build.log` (unless crosstool-NG fails before the build starts)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/7012283/build.log)

This is the error when I was building the [dcgm](https://github.com/NVIDIA/DCGM) using Dockerfile. This error happens inside the docker image. However I repeated it without the image and container as described in the [issue](https://github.com/NVIDIA/DCGM/issues/6). Please let me know if you have any ideas.

**Comment by QBos07** [comment]
this is the version of your make
do
```
ct-ng version
```
insted of
```
ct-ng --version
```
but this sounds more like a problem with the Dockerfile from dcgm

**Comment by liuyibox** [comment]
> this is the version of your make
> do
> 
> ```
> ct-ng version
> ```
> 
> insted of
> 
> ```
> ct-ng --version
> ```
> 
> but this sounds more like a problem with the Dockerfile from dcgm

Thank you. Version updated. I will check the Dockerfile from dcgm for sure.

**Comment by nikkon-dev** [comment]
@liuyibox,
Hi, the DCGM dev is here.
The current version of the published dcgmbuild Dockerfile uses the latest released version of the crosstool-ng (1.24), which cannot be used anymore due to an issue related to this commit: https://github.com/crosstool-ng/crosstool-ng/commit/89e00e661f1362add2be8d76e22a3ab7a504ab8b. 
Unfortunately, right now the only option is to manually update the Dockerfile in the DCGM and use either top-of-tree state or any specific commit after the mentioned above. 
You will also have to update the .config files to use proper version of expat library.

**Comment by cpackham** [comment]
The actual error is because somehow we've ended up with `CT_BUILD_DIR` being unset (which is what that `mkdir -p` was trying to create). The config file you've linked to is missing this so ideally you'd just add `CT_BUILD_DIR="${CT_BUILD_TOP_DIR}/build"` in the appropriate place (~ line 49).

**Comment by nikkon-dev** [comment]
@cpackham, That's one is easy to explain - CT_BUILD_DIR related logic was added after 1.24 that was used to generate the .config file.
