### ISSUE TITLE
multilib build failed when building arm-unknown-linux-gnueabi with glibc 2.3 to glibc 2.9

### ISSUE THREAD

**Issue by MikePhillyFlyers** [crosstool-ng/crosstool-ng#1651]
I am trying to build 'arm-unknown-linux-gnueabi' toolchain with glibc version in the range 2.4 to 2.9.....

the arm target I'm building for needs to be within that glibc range.. also I really need to build for linux kernel 3.10, but the error happens whether the kernel is 3.10.x or in the 4.x range......kernel version doesn't seem to matter...

The error happens at glibc-2.3 and later... at glibc-2.29 it works...

I'm using the sample arm-unknown-linux-gnueabi .config file, only changing the glibc version to 2.9, (and have to drop the isl-0.20 to isl-.18, as it can't seem to find 0.20)

**Does anyone know what the "checking sysdep dirs... configure: error: The arm is not supported." means?**

```
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[ERROR]      checking sysdep dirs... configure: error: The arm is not supported.
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library headers & start files'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@263]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1586]
[ERROR]  >>        called from: glibc_backend[scripts/build/libc/glibc.sh@74]
[ERROR]  >>        called from: glibc_start_files[scripts/build/libc/glibc.sh@38]
[ERROR]  >>        called from: do_libc_start_files[scripts/build/libc.sh@28]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 17:46.91)
[17:47] / ct-ng:261: recipe for target 'build' failed
```

attaching the build.log as well...
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/7833490/build.log)

**Comment by cpackham** [comment]
The short answer is that the oldest supported glibc version in crosstool-ng 1.24 is glibc-2.14. If you really need to build with such an old version of glibc you'll probably have to go back to an older version (and probably run on a sufficiently old build machine/container). You'd probably be better off putting effort into updating your target to a newer compiler/kernel/libc.

**Comment by MikePhillyFlyers** [comment]
> The short answer is that the oldest supported glibc version in crosstool-ng 1.24 is glibc-2.14. If you really need to build with such an old version of glibc you'll probably have to go back to an older version of crosstool-ng (and probably run it on a sufficiently old build machine/container). You'd probably be better off putting effort into updating your target to a newer compiler/kernel/libc.

Awesome... thanks so much for the reply... I didn't realize how old 2.4-2.9 really was until I looked them up in the repo....you are right, that is going back quite a number of years!

I'll try some older versions and see if I can get one to work... if only I could update the target, but it's a commercial device that I have no source code for, so I'm stuck with what is on it!

Thanks again :)

**Comment by stilor** [comment]
Sorry for being a latecomer, but @MikePhillyFlyers, did you manually edit the .config file before running the build? I find this highly  suspicious in the log:

```
[DEBUG]    CT_GLIBC_V_2_29=y
[DEBUG]    CT_GLIBC_VERSION="2.9"
```
As you see, these two lines select different versions - 2.29 and 2.9. You are not supposed to manually edit the .config file as that would violate the symbol dependencies. Those dependencies are in place for a reason. In your case, glibc prior to 2.20 had distributed the non-x86 architectures via an add-on (`glibc-ports`) that needed to be configured separately and prior to 2.17 that add-on was distributed as a separate tarball. ct-ng has build procedures in place to accommodate these version-specific quirks but since you selected 2.29 as the version, these procedures were not invoked. This is the reason for the specific error you're seeing.

Your best starting point would be to select "very old" as the `glibc`/`glibc-ports` versions and select a local directory with unpacked and patched sources for them. You will need to apply to your glibc version some/all of the patches ct-ng has for glibc-2.12.1 (@cpackham is incorrect here, the oldest supported version in 1.24.0 is 2.12.1, not 2.14) - perhaps modifying them to apply to older versions, and you might need to backport more fixes to enable those ancient versions to build on modern OS.
