### ISSUE TITLE
Error for static build in arch Linux x86_64

### ISSUE THREAD

**Issue by MOHAMED19OS** [crosstool-ng/crosstool-ng#1683]
### 

- Report crosstool-NG version : 
   HEAD: installed with brew install crosstools-ng --HEAD
- Report host OS and its version : 
 Arch Linux - x86_64 Linux 5.16.10-arch1-1 - KDE 5.91.0 / Plasma 5.24.1
- Config:
Generated config for "mipsel-unknown-linux-gnu" and some modifications
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/8101830/config.txt)

- Build.log:
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/8101833/build.log)

the error for static build  :

INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Prepare binutils for static build
[EXTRA]    Building binutils
[ERROR]    collect2: error: ld returned 1 exit status
[ERROR]    make[5]: *** [Makefile:1041: objdump] Error 1
[ERROR]    make[5]: *** Waiting for unfinished jobs....
[ERROR]    make[4]: *** [Makefile:1431: all-recursive] Error 1
[ERROR]    make[3]: *** [Makefile:875: all] Error 2
[ERROR]    make[2]: *** [Makefile:4021: all-binutils] Error 2
[ERROR]    make[1]: *** [Makefile:1001: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@209]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@70]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 4:37.09)
[04:38] / make: *** [ct-ng:261: build] Error 2

**Comment by cpackham** [comment]
Actual error is
```
[ALL  ]      CCLD     objdump
[ALL  ]    /usr/bin/ld: cannot find -ldebuginfod: No such file or directory
```

**Comment by cpackham** [comment]
I think the problem is that somehow binutils has decided to include debuginfod support. But we don't provide libdebuginfod (it's part of elfutils but we use libelf, probably a reason to do #1247).

I just tried your config and it built for me but I imagine it's just because of a different build environment.

If you've still got the output could you attach `.build/mipsel-vuplus-linux-gnu/build/build-binutils-host-x86_64-build_pc-linux-gnu/config.log`.

**Comment by cpackham** [comment]
OK I can reproduce it if I install the `libdebuginfod-dev` package on my system.

**Comment by QBos07** [comment]
This isn't the first issue with static linking. #1487 looks similar.

**Comment by cpackham** [comment]
Yeah it looks like a number of libraries are distributed as dynamic only. I
don't see any easy way of finding these (even if we had ci builds with
CT_STATIC_TOOLCHAIN=y the problems usually arise due to extra packages that
happen to be installed). I do wonder if there is some pkgconfig flag we
should be setting so that it know only to return libs that have a .a file.

**Comment by QBos07** [comment]
You could probably patch the configure scripts to include this needed flags (to know that it's building staticly) to the test cases. This flags are mostly ignored there because who really use they in there opinion.
