### ISSUE TITLE
Cannot select glibc version

### ISSUE THREAD

**Issue by tawmoto** [crosstool-ng/crosstool-ng#1740]
Hi,

I am using version 1.25.0 on Ubuntu 20.04 and I am trying to create a toolchain using GCC and glibc.
But it seems that I cannot select the `glibc` version, only `newlib` is available.
I built crostool via `./bootstrap && ./configure && make && make install`

Not sure if I am doing smth wrong or it's a bug in the latest version. (last time I used crosstool it was 5 years ago)

Thanks

![image](https://user-images.githubusercontent.com/35702340/169302556-7875b75d-d0c9-4ca3-84cb-423bc8b87292.png)

**Comment by stilor** [comment]
You have probably started from an empty configuration, which selects "bare metal" (i.e. no operating system). GLIBC requires Linux operating system to be selected. You are likely better off starting from some sample configuration, e.g. running `ct-ng x86_64-unknown-linux-gnu` and only then `ct-ng menuconfig`.

**Comment by cpackham** [comment]
Hmm my email reply doesn't appear to have made it (the one time I don't hit reply all). Pretty much what @stilor said.

> You need to select OS Linux first as glibc is dependent on that.
>
> Generally it is a good idea to start with one of the built-in samples and customize it to your needs from there e.g. `ct-ng arm-unknown-linux-gnueabi` then `ct-ng menuconfig`. You can use `ct-ng list-samples` to get a list if all the available samples.

One thing we could do that might help people is to use add a `comment "glibc requires Linux" if !OS_LINUX` to the C library menu.

**Comment by tawmoto** [comment]
Thanks a lot @cpackham, your post helped a lot. Probably I have missed this in the documentation.

**Comment by stilor** [comment]
> One thing we could do that might help people is to use add a comment "glibc requires Linux" if !OS_LINUX

I know Buildroot does show such hints, but I am on the fence as to whether they are helpful or annoying :) Packages (both here and in buildroot) have a lot of dependencies and if we add a comment for every one of them, it is cluttering the menu. Such hint wouldn't be exactly correct either, for example, it is not just Linux for glibc, but rather "Linux on a target with MMU". Same for all other components.

It is usually possible to hit '/' (search) and search for the option, but if one searches for 'glibc', it is a mess. One would have to search for 'LIBC_GLIBC' to get that kind of information, but this is non-trivial for the end users. Would have been nice if kconfig showed the disabled options (but didn't allow to choose them) so that the users could at least click [Help] to see why a certain option is unavailable... I don't see a good way to steer the users towards seeing the exact list of dependencies, unfortunately.

That said, if you think such hints would be helpful, please don't let my rant stop you :)

**Comment by cpackham** [comment]
You need to select OS Linux first as glibc is dependent on that.

Generally it is a good idea to start with one of the built-in samples and
customize it to your needs from there e.g. `ct-ng
arm-unknown-linux-gnueabi` then `ct-ng menuconfig`. You can use `ct-ng
list-samples` to get a list if all the available samples.
