### ISSUE TITLE
Error ct-ng build - Installing C Library - Cannot open jobserver

### ISSUE THREAD

**Issue by xianrecords2015** [crosstool-ng/crosstool-ng#1858]
I get the following error when running ct-ng build

[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      make[3]: *** Cannot open jobserver /var/folders/rl/bqzm84y11n1cydd5lfcgpv5c0000gn/T//GMfifo17164r: No such file or directory.  Stop.
[ERROR]      make[2]: *** [Makefile:470: csu/subdir_lib] Error 2
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step '
[ERROR]  >>        called in step '(top-level)'

This is running on macOS Big Sur 11.4

Attached build.log and .config

[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/10118674/build.log.zip)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/10118684/config.txt)

**Comment by cpackham** [comment]
Seems to be a macOS thing happens on the CI builds too. @bhundven any insights?

**Comment by cpackham** [comment]
https://lists.gnu.org/archive/html/bug-make/2022-09/msg00051.html suggests adding `--jobserver-style=pipe` might help

**Comment by cpackham** [comment]
Actually no I think this is https://sourceware.org/git/?p=glibc.git;a=commit;h=2d7ed98add14f75041499ac189696c9bd3d757fe will look at back-porting that

**Comment by xianrecords2015** [comment]
Not sure why this was closed. This is still not working

**Comment by cpackham** [comment]
It was auto-closed when the fix was merged to master.

The problem is an incompatibility between glibc's Makefiles and the latest version of GNU Make. I didn't have the bandwidth to test every version of glibc currently listed in ct-ng so I only applied the [fix](https://github.com/crosstool-ng/crosstool-ng/blob/master/packages/glibc/2.36/0006-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch) the latest version.

The fix will probably apply cleanly enough to older versions. If you want to back port the fix to an older version go for it, but I'd suggest using the latest version of glibc if you can.
