### ISSUE TITLE
undefined reference to `__divti3'

### ISSUE THREAD

**Issue by bemerguy** [crosstool-ng/crosstool-ng#1976]
crosstool-NG 1.25.0.189_1f1107f
while linking an android kernel:
bitmap.c:(.text.__ntfs_bitmap_set_bits_in_run+0xa0c): undefined reference to `__divti3'

cross (build/host: x86_64, target: aarch64)

I've searched all over about it but couldn't find anything. Tried multiple different combination of options in menuconfig but it always gives this error while linking my kernel

[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/11681083/config.zip)

**Comment by cpackham** [comment]
If the compiler is emitting a reference to that function then it must think your configuration is incapable of some integer division operation https://gcc.gnu.org/onlinedocs/gccint/Integer-library-routines.html

I notice your configuration is pointing to GCC's git repo (and not to any specific commit either) so you may just be hitting some in-flight GCC code. I'd definitely recommend sticking to the released GCC versions unless you're actually working on GCC.

For what it's worth I tried your config which picked up gcc bc5a2c2e and was able to successfully build an arm64 kernel with ntfs enabled.

**Comment by bemerguy** [comment]
I had used release/13.0.1 before with the same error. It doesn't seem to be a in-flight code ..
Try enabling CONFIG_GCOV_KERNEL, it only happens here with it enabled.
Still I don't understand how the compiler generates that opcode/instruction and the linker doesn't know?

**Comment by cpackham** [comment]
[This thread on stackoverflow](https://stackoverflow.com/questions/34532528/undefined-reference-to-divdi3) talks a bit about why GCC does this (and why the behaviour probably won't change). Because the kernel builds with `-ffree-standing` it needs to provide things in libgcc that userland applications get for free. It does have a number of those functions although `__divti3` is not one of them.

I have just tried with `CONFIG_GCOV_KERNEL` enabled and it built successfully. There might be something in those extra 5M lines android adds that does something different.

Ultimately there's nothing crosstool-ng can do about this, GCC seems to be behaving as intended.
