### ISSUE TITLE
GCC compile error when using git "*** No rule to make target '../build-x86_64-build_pc-linux-gnu/libcpp/libcpp.a"

### ISSUE THREAD

**Issue by asemjonovs** [crosstool-ng/crosstool-ng#2026]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version: 1.25.0
- Report host OS and its version: Linux 6.3.11-1rodete1-amd64
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

Error
```
[INFO ]  Installing core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[ERROR]    make[2]: *** No rule to make target '../build-x86_64-build_pc-linux-gnu/libcpp/libcpp.a', needed by 'build/genmatch'.  Stop.
[ERROR]    make[2]: *** Waiting for unfinished jobs...
.
```
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/12525606/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/12525625/config.txt)
[build.1.log](https://github.com/crosstool-ng/crosstool-ng/files/12525796/build.1.log)

**Comment by cpackham** [comment]
It looks like you're using something from the [Zephyr project](https://github.com/zephyrproject-rtos). You might have better luck reporting it over there.

The problem with `build/genmatch` does vaguely ring a bell but not loudly enough for me to point to a specific fix.

For what it's worth I tried to adapt your config to the current ct-ng and it got past the `Installing core C gcc compiler` .

**Comment by asemjonovs** [comment]
Thanks for taking a look.  Unfortunately I still get the same error when using GCC's github mirror as well, so I don't think its specific to Zephyr.  Could it be something in my environment?  Here's the output with using `https://github.com/gcc-mirror/gcc`

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/12539461/build.log)
[config_gcc.txt](https://github.com/crosstool-ng/crosstool-ng/files/12539510/config_gcc.txt)

**Comment by cpackham** [comment]
You're still trying to build arbitrary GCC code instead of a released version so I'm not entirely surprised you're hitting issues.

Because you're using crosstool-ng-1.25.0 I think critically your are missing

https://github.com/crosstool-ng/crosstool-ng/commit/db6f703f52e33a5791c5c2728fa1e3a330a08e98
and
https://github.com/crosstool-ng/crosstool-ng/commit/3d706748b49f9fa5adda5553227ddf16a1b0d552

That's the bell that was ringing when I saw `build/genmatch`

You'll probably have better luck with crosstool-ng from master or you could take the freshly minted [crosstool-ng-1.26.0_rc1.tar.xz](https://github.com/crosstool-ng/crosstool-ng/releases/download/crosstool-ng-1.26.0-rc1/crosstool-ng-1.26.0_rc1.tar.xz) for a spin

**Comment by asemjonovs** [comment]
I tried out [crosstool-ng-1.26.0_rc1.tar.xz](https://github.com/crosstool-ng/crosstool-ng/releases/download/crosstool-ng-1.26.0-rc1/crosstool-ng-1.26.0_rc1.tar.xz) and that resolved my issue!  Thanks for your help :smiley:

**Comment by cpackham** [comment]
Resolved with latest ct-ng. Closing.
