### ISSUE TITLE
[ERROR] configure: error: expat is missing or unusable should probably be error: *lib*expat is missing

### ISSUE THREAD

**Issue by voltagex** [crosstool-ng/crosstool-ng#209]
I got `[ERROR]    configure: error: expat is missing or unusable` so I installed the expat package. After yet another 15 minute build I got the same error. So the package I actually need is libexpat-dev. 

1. Is there a way to check all these prerequisites *before* doing ct-ng build

2. Should the error actually reference libexpat to reduce confusion?

**Comment by jasmin-j** [comment]
> Is there a way to check all these prerequisites before doing ct-ng build

CT-NG is designed to do all of this automatically. So there must be a mistake
in your configuration, or something is missing in CT-NG for your particular
cross compiler.
Please have look to my comments in #208.

**Comment by voltagex** [comment]
It's defiinitely not checking prereqs. I spun up a new AWS instance, installed build-essential and built the rpi2 sample but got 
```
[INFO ]  Installing cross-gdb 
[ERROR]    configure: error: python is missing or unusable
```
at the last moment.

**Comment by jasmin-j** [comment]
> It's defiinitely not checking prereqs. I spun up a new AWS instance, installed build-essential and
> built the rpi2 sample but got

OK, with Python you are right. But it can't install Python automatically. It might be possible to do a check at the beginning, when GDB is configured with Python support to save time. Currently it relies on the configure checks of the packages.
But it installs/downloads all packages it requires to build a toolchain.

If you don't have Python or don't want to install it, you can disable Python in GDB with "Enable python scripting" = n.
It is automatically disabled, if you build a static GDB version "Build a static cross gdb" = y

**Comment by voltagex** [comment]
Okay. That one makes sense, but back to the issue of the expat error not being particularly clear?

**Comment by voltagex** [comment]
I

**Comment by bhundven** [comment]
Just FYI, if you want python scripting, just install python-dev. It isn't a dependency of build-essential.

**Comment by jasmin-j** [comment]
> Just FYI, if you want python scripting, just install python-dev. It isn't a dependency of build-essential.

@bhundven:
Possible solutions:
- Adding a check for the required Python libraries to crosstool-NG.sh before the build really starts, which gets executed if CT_GDB_CROSS_PYTHON is "y".
- Adding a hint to install python-dev to the help text of the GDB_CROSS_PYTHON option.
- Adding a CT_NG configure option to configure.ac, which will check for the required libraries and print an error if they are not found. The configure option can be used to __disable__ this check, so that it is done defaultly.
- Do nothing.

I would vote for adding it to the help text. Then it is documented and users can't complain they didn't know ;)
