### ISSUE TITLE
mpfr.org is down

### ISSUE THREAD

**Issue by Phyks** [crosstool-ng/crosstool-ng#250]
Hi,

`mpfr.org` is down at the moment (maybe not permanent, but has been down for a few hours, and had been frequently down in the past according to some google results), which prevents from building `crosstool-ng`.

Maybe it could be a good idea to use `https://ftp.gnu.org/gnu/mpfr/` instead? I tried to make the build scripts use it, but should have missed something as it does not seem to work either…

Thanks

**Comment by bhundven** [comment]
Indeed. I will add that mirror when I get back to my computer.

**Comment by mingwandroid** [comment]
mpfr.org has been yo-yo-esque for many-a-year now.

**Comment by bhundven** [comment]
Well, while mpfr.org is down, the timeout should happen and roll over to gnu.org:
https://github.com/crosstool-ng/crosstool-ng/blob/master/scripts/build/companion_libs/110-mpfr.sh#L14

But, since mpfr.org is a yo-yo, as @mingwandroid said, I'll move the mirrors around so mpfr.org is the backup instead of the primary.

**Comment by bhundven** [comment]
Rock and roll! pull the latest master and build like a mad man!

**Comment by Phyks** [comment]
Thanks!
