### ISSUE TITLE
Rework the download mechanism

### ISSUE THREAD

**Issue by tpetazzoni** [crosstool-ng/crosstool-ng#3]
The current download mechanism in Crosstool-NG has a pretty annoying behavior: it tries a large number of URLs to download each single file, even though most of those URLs simply don't work. In some networks, some of those URLs simply require wget/curl to time out, which makes the download process very slow.

The download mechanism should be simplified, and simply download from the well-known official upstream location of each component. Potentially a fallback to one single mirror site maintained by Crosstool-NG could be added, but generally all upstreams for components packaged by Crosstool-NG are fairly active and stable, so this may not even be necessary.

**Comment by bhundven** [comment]
@tpetazzoni I'll be working on this issue tomorrow. I don't know if @yann-morin-1998 knows if there are any data;I/O limitations with crosstool-ng.org (aka osuosl), but I'll look into mirroring source archives on crosstool-ng.org as well and making that the first mirror the build tries.

**Comment by bhundven** [comment]
I have opened pull request #40 
@tpetazzoni would you mind reviewing?

**Comment by tpetazzoni** [comment]
Thanks for working on this! However, I must say I was hoping for a more radical change: your proposal continues to try gazillions of servers, gazillions of possible file extensions, so many requests are needed before actually finding the right file. What about simply have one URL for each file to be downloaded, and that's it? Trying tar.xz, tar.bz2, tar.gz, on multiple servers is quite silly IMO.

**Comment by bhundven** [comment]
@tpetazzoni There will be a rewrite of the download mechanism soon. I've had a few conversations about this with others. I'd like to separate out protocols, as well as download mirrors by region.
At the same time, I'd like to get a stable 1.20.1 release out so that I can stop seeing people complain about arm hard-float issues in 1.20.0.

I also have a pull request in to remove eglibc, so that I can clean up and refactor glibc's build to be 2-pass, but that won't happen until after 1.20.1.

The last bit to be done before 1.20.1 is to update the way out of date docs/ directory.

You're always welcome to open a pull-request and make the updates you'd like to see!
I'm going to commit this change and close this issue.

But I will remember to add refactoring the download mechanism to the 1.21.0 release milestone!
