### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by lilred** [crosstool-ng/crosstool-ng#325]
It would be lovely if crosstool-NG had a package in Debian and Ubuntu :)

**Comment by voltagex** [comment]
The packaging is there in the debian/ subdirectory - if you need it right now, `git-buildpackage -us -uc` will work.

People have tried in Debian before: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=695545, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=721430, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=695586. It seems like there wasn't enough interest / spare time

Ubuntu is a bit different, debian/control needs to be edited because libtool-bin is libtool in recent Ubuntu versions. I can't find any reference to an Ubuntu package existing, but I'm not quite sure where to look. I'm sure the build scripts could be fixed to work on both if needed.

**Comment by bhundven** [comment]
This is not a crosstool-ng issue, it is a problem with your upstream distribution. Open a bug/issue with them.
