### ISSUE TITLE
ncurses breaks make

### ISSUE THREAD

**Issue by attilaolah** [crosstool-ng/crosstool-ng#34]
When I run `./bootstrap && ./configure && make`, I get:

```
  LD     'mconf'
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/../../../../x86_64-pc-linux-gnu/bin/ld: lxdialog/util.o: undefined reference to symbol 'cbreak'
/lib64/libtinfow.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:100: recipe for target 'mconf' failed
make[2]: *** [mconf] Error 1
Makefile:166: recipe for target 'build-lib-kconfig' failed
make[1]: *** [build-lib-kconfig] Error 2
Makefile:126: recipe for target 'build' failed
make: *** [build] Error 2
```

My `ncurses` is `sys-lib/ncurses-5.9-r3`, built `--with-cxx --with-tinfo --with-unicode` and `--without` everything else.

A few related bugs can be found [here][1], if that helps.

[1]: http://gentoobrowse.randomdan.homeip.net/package/sys-libs/ncurses

**Comment by bhundven** [comment]
Could you point me to a specific bug number?
I flipped through a few of them, but don't see anything related.

I don't have any issues with Debian, Fedora, CentOS7, or ArchLinux. Could this be yet another issue with gentoo's ncurses? If so, shouldn't the bug be opened with them?
I'm making some assumptions, because there isn't a whole lot of information provided in this issue. If I'm wrong, please provide more info! :)

**Comment by attilaolah** [comment]
Alright, let me migrate this to the Gentoo forks.
