### ISSUE TITLE
Patch glibc for CVE-2015-7547

### ISSUE THREAD

**Issue by breser** [crosstool-ng/crosstool-ng#341]
See details here:
https://googleonlinesecurity.blogspot.com/2016/02/cve-2015-7547-glibc-getaddrinfo-stack.html

**Comment by bhundven** [comment]
@breser I see the CVE says that the bug was introduced in glibc-2.9.
In the master branch, I will soon be cutting down the number of glibc versions to 2.22 down to 2.18.
But the 1.22 branch will be maintained for a while will still have a lot of glibc versions.

I currently don't have time to backport this patch to all the glibc versions. I'm open to the idea of anyone else providing a backport. :)

**Comment by bhundven** [comment]
2.23 is in. I'm in the middle of cleaning up glibc.sh, so I will backport the CVE when I get done with the clean up.

**Comment by breser** [comment]
I'd already created the 2.22 backport.  Patch is on this pull request:
https://github.com/crosstool-ng/crosstool-ng/pull/366

I haven't bothered to backport it to other releases.  But I'd imagine it's not difficult.

**Comment by bhundven** [comment]
Thanks!

**Comment by bhundven** [comment]
I will merge this soon!

**Comment by iokill** [comment]
Any details when crosstool-ng 1.23 will hit? It'd be great to have a release with a recent glibc version and CVE-2015-7547 fixed. :)

**Comment by bhundven** [comment]
@breser The backport to 2.22 has been merged.

Thank you!
