### ISSUE TITLE
using other CT_ variables in CT_WORK_DIR creates bogus directory

### ISSUE THREAD

**Issue by stefanct** [crosstool-ng/crosstool-ng#38]
In my configuration I use an absolute path followed by `${CT_TARGET}` as `$CT_WORK_DIR`:
`/.../build-${CT_TARGET}`. Apparently ct-ng is using `$CT_WORK_DIR` before that and creates its `tools` directory there containing `awk`, `bash` etc. but because the `${CT_TARGET}` variable is unset at the time it creates `/.../build-` (sic!) instead. Apparently this is only a cosmetic problem.

The help text for `$CT_WORK_DIR` does state that one should not change it, but I deem that a rather obvious feature.

**Comment by bhundven** [comment]
I will look into this, unless you supply a patch to fix this.

**Comment by stefanct** [comment]
I don't care enough TBH, sorry :)

**Comment by bhundven** [comment]
Talking with @yann-morin-1998, the CT_WORK_DIR was not intended to contain other ct-ng config variables. This issue could be fixed with a lot of hacking around how we read a config (i.e. making a recursive function that reads in the config, but currently there are much bigger fish to fry.

I'm closing this as wontfix, but I may come back to this in the future.
