### ISSUE TITLE
file permissions on scripts: rpmlint warnings about installed files

### ISSUE THREAD

**Issue by 15knots** [crosstool-ng/crosstool-ng#433]
When I package crosstool-ng as an RPM for opensuse, I get some warnings from rpmlint concerning file executable permissions after an `make install` .
I could blindly shut down the warnings in the RPM-specfile, but I prefer to get some feedback from  Upstream before doing that.

Errors are:
1.  `crosstool-ng.i586: W: script-without-shebang 
   This text file has executable bits set or is located in a path dedicated for executables, but lacks a shebang and cannot thus be executed.  If the file is meant to be an executable script, add the shebang, otherwise remove the executable bits or move the file elsewhere.`
   File: /usr/lib/crosstool-ng/kconfig/kconfig.mk
2. `crosstool-ng.i586: W: non-executable-script
   This text file contains a shebang or is located in a path dedicated for executables, but lacks the executable bits and cannot thus be executed.  If the file is meant to be an executable script, add the executable bits, otherwise remove the shebang or move the file elsewhere.`
   Files:
   /usr/lib/crosstool-ng/scripts/populate.in 0644L /bin/sh
   /usr/lib/crosstool-ng/patches/glibc/ports-2.12.1/170-localedef-fix-trampoline.patch 0644L /bin/sh
   /usr/lib/crosstool-ng/patches/binutils/2.20.1a/270-better_file_error.patch 0644L /bin/sh
   /usr/lib/crosstool-ng/scripts/build/debug/duma.in 0644L /bin/sh
   /usr/lib/crosstool-ng/scripts/toolchain-config.in 0644L /bin/sh
   /usr/lib/crosstool-ng/patches/glibc/ports-2.13/170-localedef-fix-trampoline.patch 0644L /bin/sh
   /usr/lib/crosstool-ng/patches/binutils/2.20.1a/140-check_ldrunpath_length.patch 0644L /bin/sh
   /usr/lib/crosstool-ng/patches/glibc/ports-2.10.1/170-localedef-fix-trampoline.patch 0644L /bin/sh

For [1], I could simply remove the executable permission, looks like it gets set by `make install`.
For [2], I need advice or fixes from upstream.

BTW, RPM repos are at http://download.opensuse.org/repositories/home:/15knots/ , overview is here https://build.opensuse.org/package/show/home:15knots/crosstool-ng

**Comment by 15knots** [comment]
Content of `/usr/lib/crosstool-ng/` after installation is:
/usr/lib/crosstool-ng/kconfig/:
insgesamt 404
-rwxr-xr-x 1 399 399 110799 26. Aug 23:01 conf
-rwxr-xr-x 1 399 399   2923 26. Aug 23:01 kconfig.mk
-rwxr-xr-x 1 399 399 155037 26. Aug 23:01 mconf
-rwxr-xr-x 1 399 399 138839 26. Aug 23:01 nconf

**Comment by stilor** [comment]
On [1]: indeed, needs to be fixed.
On [2]: the `*.in` files are shell script *templates*. They are not expected to execute out of the box; rather, they are preprocessed and included into the final toolchain. These warnings likely need to be silenced in the spec.
On [2]: the `*.patch` files are dual-use - they can be either fed to patch utility, or they can be run as a shell script. Crosstool-NG does not use these dubious "enhanced patches" as a shell script, just as a plain patch. It looks like these patches have been downloaded from somewhere, but I couldn't find the origin of such formatting - google search points back to crosstool-ng. So, the bottom line - they should've been converted to regular patches, butthe affected versions are no longer supported on master - so these patches have been removed since.

**Comment by stilor** [comment]
This should be fixed by #738 which addressed these issues for Debian packaging.
