### ISSUE TITLE
Build error in Ubuntu 16.04

### ISSUE THREAD

**Issue by IQYottabit** [crosstool-ng/crosstool-ng#581]
I followed the step which is mentioned in help. I m using crosstool-ng-1.9.3

I configured to my local folder, $ ./configure --prefix=/opt/toolchains/
Then it asked me to run make, make install. I got an error during make, don't know why I got this error ?

This is the following error I got. 
ixx:~/Downloads/crosstool-ng-1.9.3$ make
make[11570]: fork: Resource temporarily unavailable
Makefile:90: recipe for target 'build' failed
make[11569]: *** [build] Error 2
Makefile:90: recipe for target 'build' failed
make[11568]: *** [build] Error 2

 P S : BTW. git clone of repo I didnt get this bug. Only from the download I got following problem.

Investigation from my side : checked the limit in shell, i didnt touch maximum limit. 
>$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62706
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 10240
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 62706
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by stilor** [comment]
Judging from "make[11570]", the makefile somehow ended up calling itself recursively until it exhausted system memory. Current Makefiles in 1.22 and on master have some protection against recursion.

The release you're using (1.9.3) is no longer supported and this is unlikely to get fixed in that release. You may need to backport the relevant changes yourself if you really need to use 1.9.3. As you confirmed, 'make' from the repository works fine.

Hence, closing this issue.
