### ISSUE TITLE
Linking failure in glibc 2.12 (recent regression)

### ISSUE THREAD

**Issue by tamird** [crosstool-ng/crosstool-ng#616]
The proximate cause is:
```
/build/.build/x86_64-unknown-linux-gnu/buildtools/lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: /build/.build/x86_64-unknown-linux-gnu/build/build-libc-final/multilib/elf/librtld.os: relocation R_X86_64_PC32 against undefined hidden symbol `rtld_errno' can not be used when making a shared object
```

`build.log` and `.config`: https://gist.github.com/tamird/064b76c7dc75c17f794458420a1cd02e

Things work with 4d17f393bdecbef632f4f6e2aa6ec44951c5a4c4 but not with 4de4507, so this is a regression introduced somewhere in https://github.com/crosstool-ng/crosstool-ng/compare/4d17f393bdecbef632f4f6e2aa6ec44951c5a4c4...4de4507

**Comment by stilor** [comment]
Your `.config` works for me on Ubuntu 16.10 host. What is your host system?
The `build.log` on gist is truncated.

**Comment by tamird** [comment]
The host system is ubuntu 16.04.

here's the Dockerfile we're using to build this (the .config I supplied is https://github.com/cockroachdb/cockroach/blob/master/build/x86-linux-gnu.config): https://github.com/cockroachdb/cockroach/blob/master/build/Dockerfile#L80

**Comment by tamird** [comment]
You're right, here's the full log 
[build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/797819/build.log.gz)

**Comment by stilor** [comment]
I finally got to look at this issue. The problem is that your Dockerfile does not do `ct-ng oldconfig` after copying the config file. If the underlying Kconfig scripts have changed, this results in variables not set properly.

In you case, it seems the culprit was that the outdated .config resulted in disabling the TLS, which apparently broke glibc build.

I am thinking of doing an equivalent of `ct-ng oldconfig` as a part of `ct-ng build`. For now, however, either do `ct-ng oldconfig` explicitly, or (this may be even better alternative) save the "defconfig" rather than full config, and use `ct-ng defconfig`.
