### ISSUE TITLE
gcc-5.4.0/libmpx/mpxrt/mpxrt.c:70:23: error: 'REG_RIP' undeclared

### ISSUE THREAD

**Issue by vmurashev** [crosstool-ng/crosstool-ng#621]
crosstool-ng is used from master
I do defconfig using the following options:
CT_CC_GCC_VERSION="5.4.0"
CT_CC_GCC_V_5_4_0=y
CT_CC_LANG_CXX=y
CT_ARCH_x86=y
CT_ARCH_64=y
CT_LIBC="glibc"
CT_LIBC_glibc=y
CT_LIBC_VERSION="2.12.2"
CT_LIBC_GLIBC_V_2_12_2=y
CT_OBSOLETE=y
CT_KERNEL_linux=y
CT_KERNEL_V_2_6_32=y
CT_MULTILIB=y

i.e. I am trying to build cross-compiler with muiltilib support (and expect that target binaries will work on centos6)
Finally build fails with the following error:
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    /home/vet/me/ct-dev/stable/output/obj/x86_64-unknown-linux-gnu/.build/src/gcc-5.4.0/libmpx/mpxrt/mpxrt.c:70:23: error: 'REG_RIP' undeclared (first use in this function)
[ERROR]    gmake[6]: *** [libmpx_la-mpxrt.lo] Error 1
[ERROR]    gmake[6]: *** Waiting for unfinished jobs....
[ERROR]    gmake[5]: *** [all-recursive] Error 1
[ERROR]    gmake[4]: *** [all] Error 2
[ERROR]    gmake[3]: *** [all-target-libmpx] Error 2
[ERROR]    gmake[3]: *** Waiting for unfinished jobs....
[ERROR]    gmake[2]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@331]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/100-gcc.sh@1137]
[ERROR]  >>        called from: do_gcc_for_host[scripts/build/cc/100-gcc.sh@838]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc.sh@56]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]

**Comment by vmurashev** [comment]
At the same time there is no such problem, when I avoid use of old version glibc and kernel-headers.
i.e. there are no build issues when I defconfig and build on
CT_CC_GCC_VERSION="5.4.0"
CT_CC_GCC_V_5_4_0=y
CT_CC_LANG_CXX=y
CT_ARCH_x86=y
CT_ARCH_64=y
CT_LIBC="glibc"
CT_LIBC_glibc=y
CT_KERNEL_linux=y
CT_MULTILIB=y

**Comment by stilor** [comment]
Newer glibc have a combined tree for the x86_64 and i386 headers, so the build script just installs headers once per sysroot (some architectures use separate sysroots with different multilib variants). I don't remember exactly in which version x86_64/i386 headers were finally merged, and I can't immediately think of a test to detect it before installing the headers. Note that `ucontext.h` may not be the only conflicting header.

If you can find out the glibc release that finally merged them, then a fix for older releases may be implemented similar to what uClibc/musl do (installing headers into /usr/include/$(multiarch) for all but default). If you're interested in supporting multilib for older glibcs, please submit a PR with the changes. Otherwise, I'm inclined to just consider multilib unsupported for them.
