### ISSUE TITLE
Build fails for sh4/Linux: multiple definition of `__libc_multiple_libcs'

### ISSUE THREAD

**Issue by CyberShadow** [crosstool-ng/crosstool-ng#686]
Trying to build for sh4/Linux results in linker errors while building glibc.

Steps to reproduce:

- In `ct-ng menuconfig`:
  - In `Target Options`:
    - In `Target Architecture`:
      - Select `sh`
    - In `Variant`:
      - Select `sh4`
  - In `Operating System`:
    - In `Target OS`:
      - Select `Linux`
- Run `ct-ng build`.

Full config and build log: https://gist.github.com/CyberShadow/2b55a69018c6d678a3345a3056b128fd

crosstool-NG version crosstool-ng-1.22.0 running on Arch Linux x86_64.

**Comment by CyberShadow** [comment]
Just saw http://crosstool-ng.github.io/support/, consider adding a `CONTRIBUTING.md` or `ISSUE_TEMPLATE.md` with a link to it.

Added `build.1.log` to the gist with the build log from `ct-ng build.1` (which fails with the same errors).

**Comment by stilor** [comment]
It is a known problem with glibc when GCC5 or newer is used, see this thread: https://sourceware.org/ml/libc-alpha/2017-01/msg00506.html

On crosstool-NG `master`, there is a patch to glibc that fixes this issue:
https://github.com/crosstool-ng/crosstool-ng/blob/master/patches/glibc/2.25/110-sh-fix-gcc6.patch

The patch is accepted upstream: https://sourceware.org/git/?p=glibc.git;a=commit;h=d40dbe722f004f999b589de776f7e57e564dda01

**Comment by CyberShadow** [comment]
Thank you very much for the quick reply, I've confirmed that using the git version of `crosstool-ng` works. I couldn't find an existing issue mentioning `__libc_multiple_libcs`.

**Comment by stilor** [comment]
I don't think there is a bug in glibc's bug DB for that issue and the reports in the mailing lists are harder to find since the names of the conflicting symbols change from version to version (and from architecture to architecture - other architectures had similar issues with GCC5 at some point). The problem is that GCC5 started generating calls to `abort()` to mark the code paths it believes to be invalid - which pulls in some objects from libc_nonshared.a into RTLD that are not supposed to be pulled.

**Comment by lilianmoraru** [comment]
Note that this can also appear when using `-fstack-protector-strong`.

**Comment by stilor** [comment]
I guess the underlying reason is the same: ld.so pulls in `abort` which in turn pulls in a lot of other libc stuff that is not supposed to go into ld.so. This is something you should report to glibc maintainers, not here  - they have better knowledge if `-fstack-protector-strong` is supported/requires some additional setup/etc.

**Comment by lilianmoraru** [comment]
My intention was not to report the issue here.
I was trying to solve this issue and managed to track it down in the end, so I left that info for other people in case they pass by, because this is the first result on Google when searching for this issue.

**Comment by qiubin2016** [comment]
you can try "make clean && make install"
