### ISSUE TITLE
support final installation locations besides /

### ISSUE THREAD

**Issue by benjaminp** [crosstool-ng/crosstool-ng#688]
I would like to be able to build "root" systems and toolchains that are not installed at `/`. (This is useful for building runtimes that do not interfere with the rest of the system.) I can almost achieve this now by setting `CT_PREFIX_DIR` to the desired location. However, there's still a bit of trouble due to the fact that crosstool-NG hardcodes `-prefix=/usr` when calling many `configure` scripts. One important consequence of that is that glibc dynamic linker's default rpath ends up being `/usr/lib` and `/lib` no matter what `CT_PREFIX_DIR` is. Ideally, `ld.so` would have a builtin rpath that points into the sysroot.

**Comment by stilor** [comment]
I don't quite understand whether your issue is with the toolchain installation path, or the target sysroot layout. The `CT_PREFIX_DIR` refers to the toolchain on the **host**, but `--prefix=/usr` refers to the path used by the binaries on the **target**.

The toolchain itself should be mostly relocatable, with a few caveats. It should be possible to move the toolchain from `CT_PREFIX_DIR` to another location and it should still work. Changing the target prefix is more involved, since GLIBC assumes a certain layout. I am not planning to change that (and any PR that implements that should not break any of the existing samples and, heh, not double the size of the build scripts :)).

**Comment by benjaminp** [comment]
Sorry for not being clear. I'm talking about the target installation location. By always passing `--prefix=/usr` to target libraries, crosstool-NG bakes `/` into the them. The default rpath is the main one I've run into so far, but I expect libraries compiled with `--prefix=/usr` will also try to find their data files in `/usr/share` rather than the intended sysroot installation location.

I know glibc is quite finicky about `--prefix`, but I think you can get it to do the right thing by setting `slibdir` as a config param:
```
echo `slibdir=$MYROOT/lib` > configparams
./configure --prefix=$MYROOT --libdir=$MYROOT/usr/lib
```

**Comment by stilor** [comment]
I don't think the use case for this feature is big enough to spend my time on it. If someone implements it and submits a PR - I'll consider merging it so long as it does not break the standard installation paths and does not bring a lot of code that needs to be maintained.

Hence, closing this issue.
