### ISSUE TITLE
Speeding Up Build

### ISSUE THREAD

**Issue by aogriffiths** [crosstool-ng/crosstool-ng#701]
Hi

I'm building a toolchain into a docker images and need to regularly rebuild it; the trouble is it takes ages! I don't have the fastest internet connection but even after the tarballs have been downloaded the installing steps are very slow. The "Installing final gcc compiler" step can take well over an hour.

 Can anyone give me any tips for speeding things up? For example:

- Is there a way to download all the tarbars in advance and not need to re-download them every time I make the toolchain? 
- Can I reliably do incremental builds, i.e. not have to `make clean` every time?
- Any other tips?

Thanks
Adam

P.S. Following the issue submission guidelines here's my environment:

- Using crosstool-NG as part of https://github.com/pfalcon/esp-open-sdk so this version: https://github.com/jcmvbkbc/crosstool-NG/tree/37b07f6fbea2e5d23434f7e91614528f839db056

- Working on a macbook pro. The build environment is the Debian docker container. (Docker setup is a standard docker machine, which uses Tiny Core Linux, running on VirtualBox on the Mac - but none of that should matter because as far as the crosstool-NG build scripts are concerned they are running in the Debian container)

### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by davydnorris** [comment]
You can set the values:
```
CT_SAVE_TARBALLS=y
CT_LOCAL_TARBALLS_DIR="<someplace safe>"
```
and the tarballs will then only be downloaded if they don't exist.

I'm currently working on some updates to esp-open-sdk Makefile, and I am currently building the ESP SDK with the HEAD from here. A full build takes me about 70mins under Cygwin64.

Can I ask why you need to regularly rebuild the toolchain? My approach has always been to build a standard baseline and put it under version control, and then populate your docker images by pulling this baseline. Then the only time you need to rebuild is when you want a new toolchain baseline, and you do it in a separate environment, check that it works, check it in on top of the old one as a new baseline, and finally tell your docker images to use the new base.

**Comment by stilor** [comment]
In addition to the tarball saving hint above:

Yes, ct-ng can restart a build from a certain step (see "Debug Crosstool-NG" -> "Save intermediate steps"; `ct-ng list-steps` for list of steps). But you cannot change a configuration if you restart - it is only useful for debugging build scripts, where you can repeat a failing step rather than start the build anew.

That said, the time the build takes depends heavily on the configuration. Multilib, C++ support, multiple variants of GDB (native, cross, gdbserver) all add considerable time. Some time ago it was suggested to reuse packages for build/host if possible - however, the submitter of that proposal has yet to come up with a design, let alone implementation of that feature.

As to the host, cygwin is very slow, in my experience (approximately 5 times slower than on Linux natively). For example, xtensa sample build takes about 15 minutes for me. I am not using docker to test other OSes (using KVM - that has speeds quite close to native).

**Comment by aogriffiths** [comment]
Thanks for your comments. The reasons I end up re-building are firstly, if I change something in the Dockerfile which happens before the `make` step (might not be able to avoid this). But secondly, I'm making different flavours of the build. For the esp-open-sdk that includes a "standalone" and "bare" build, both of which take hours and repeat many of the same steps. I'm thinking if I can run something like:

1. `make` to do a base build, saved as a docker image.
2. `make STANDALONE=n` on top of the base docker image to make a **bare** docker image
3. `make STANDALONE=y` on top of the base docker image to make a **standalone** docker image

Then, later if I need to reconfigure steps 2 and 3 in any way, all I will be doing is an incremental build on top of the original base image.

**Comment by davydnorris** [comment]
I'm still not quite sure exactly why you might want to rebuild the ESP8266 toolchain in various different ways so much - I'd love to understand why you're doing it, but perhaps that's a discussion we can have in the Compiler Chat section of the forums on www.esp8266.com?

Having said that, this is not really a crosstool-NG native issue. In fact it's not even really a crosstool-NG xtensa issue, it's an esp-open-sdk issue. My recommendation is to close this issue and start a topic in the esp8266 forum and I'll jump on it and discuss with you there. 

I think there's definitely ways to speed up your build - but I still want to get to the bottom of why you need to build esp-open-sdk so often :-)

**Comment by davydnorris** [comment]
@stilor -you talk about Cygwin being extremely slow, but I'd love to know what speeds you expect.

I have semi limited choice in the matter - I run Windows 10 on my laptop and am compiling for several different micros as well as doing the web front end. It would drive me nuts to have to boot up a VM for every little change I have to make. I also want more than just a compiler so minGW is not an option.

When you say your build takes 15 mins, is that from a completely empty crosstool? So ./bootstrap to final installation? That's a huge difference

**Comment by stilor** [comment]
I compared the same sample on two machines. One is my laptop, which is an Core i7-3740QM (4 cores/8 threads), 16G RAM and runs Ubuntu 17.04. The second is Core i7-5920K (6 cores/12 threads), 32G RAM and runs Windows 10 + Cygwin. Both have Samsung SSDs for the disk. Presumably, the 2nd machine should be much faster. However, the time it takes to build the xtensa-fsf-linux-uclibc: 

Ubuntu: 0:18:51
Cygwin: 2:01:47
~6.4 times slower

As to bootstrap-configure-make, it is negligible when compared to the overall time it takes to build any configuration. On Ubuntu, it takes about 4 seconds. But it highlights why Cygwin is slow: AFAIU, the emulation of fork() on Cygwin is slow, so even simple configure tests take noticeable time. The compilation itself is slower too, but to much less extent.

**Comment by mingwandroid** [comment]
On cygwin, I come building gettext takes absolutely ages, far longer proportionally than everything else (yes this is completely unscientific; I have no numbers .. hmm displaying the time to build each stage would be useful I think).

**Comment by bhundven** [comment]
@aogriffiths I just want to verify that you are building crosstool-ng from our repo?
https://github.com/pfalcon/esp-open-sdk/issues/257

That tree is out of date.

**Comment by bhundven** [comment]
@mingwandroid Is there any way to profile the activities to find out what is taking so long?
I don't have a windows installation, and I really just destroy my windows installs when I did. I suck at windows. :/
If we can isolate the slowness, maybe there is something we can do.

**Comment by davydnorris** [comment]
> @mingwandroid Is there any way to profile the activities to find out what is taking so long?
I don't have a windows installation, and I really just destroy my windows installs when I did. I suck at windows. :/
If we can isolate the slowness, maybe there is something we can do.

@bhundven - this is really a Cygwin thing, not a crosstool or esp-open-sdk thing. I know MinGW is faster but Cygwin gives me all the *nix I need in my Windows environment without having to bounce between boot partitions or a VM, and the final ESP build chain is completely fine for any builds you ever need. So I just suck up the build time for the toolchain, because it's not like you build that every day!

The OP's (@aogriffiths ) requirements are really not common at all, and I would love to take his discussion to the forums to understand what his goal is, but there are definitely changes we can make to the esp-open-sdk build process that will make it more flexible, and much faster for the OP's original requirements.

I am currently in the process of refactoring the Makefile to 
- remove some of the annoying make warnings
- improve the sdk download/build/patch/install process
- set up so that the esk-open-sdk git repo is not polluted at all, or at very least can be properly cleaned
- follow the crosstool-NG guidelines around bare metal toolchains not using sysroot, while still allowing standalone and non-standalone builds

I have also taken the very latest esp-open-sdk pull, moved the crosstool-NG submodule aside and dropped in the very latest crosstool-NG pull instead, and then built a gcc-6.3.0 based toolchain, which I tested last night and appears to work perfectly. Very little is required to get it to work (essentially copy up the samples, overlays and patches - I needed to make trivial changes to 2 patches for 6.3.0). I figure if we could get these pulled into the base crosstool, then @jcmvbkbc's fork would not need to be maintained, but instead could be used to focus on his work done on a more sustainable newlib and the other build components. (not trying to take anything away from you Max - you are a dead set LEGEND in the ESP world!!! I could not have gotten off the ground without your invaluable work)

I feel this whole thing is better discussed in the www.esp8266.com forums instead of in an issue report, hopefully everyone here agrees.

PS: WRT testing stuff on Cygwin - count me in!

**Comment by davydnorris** [comment]
@aogriffiths - let's chat somewhere else about your needs. I am pretty sure you should be able to run the esp-open-sdk make targets to get exactly what you want. But even if you did this:
```
make STANDALONE=n TOOLCHAIN=/somedir/nostandalone
make STANDALONE=y TOOLCHAIN=/somedir/standalone
```
From what I can see, ct-ng will recreate the directory structure in the new location, and run the build which will not rebuild the world - it will just install all the already built tools. The SDK will not be downloaded again, it will just be patched into the new folder structure.

**Comment by stilor** [comment]
Seems like there is no fixable issue in ct-ng, just a general discussion. Closing.
