### ISSUE TITLE
ct-ng deletes ~/.config

### ISSUE THREAD

**Issue by howey** [crosstool-ng/crosstool-ng#751]
crosstool-ng-1.23.0-79-gf7c9ab3 on Linux. At one point I had noticed that my ~/.config, the directory where many programs store their user data, had been blown away and replaced by ct-ng's .config file. Yes, the entire ~/.config directory. This has had the effect of resetting many of my programs to their default settings, such as bookmarks getting deleted and my window manager customizations being reset.

I am almost positive that this was done by the following line in the distclean target:

`$(SILENT)rm -f .config .config.* ..config*`

If it is run from ~, rm -f ..config* will remove the directory ~/.config without confirmation.

I can't recall exactly what I was doing, but I must have run ct-ng from ~, and at some point the distclean target was invoked and blew away my ~/.config.

I suggest changing the above command in the distclean target to `$(SILENT)rm -f .config` to avoid this issue, or to restrict the command only to a known list of .config* files that ct-ng knows about.

**Comment by stilor** [comment]
`rm -f` does not remove directories; one needs to pass `-r` for that.

````
$ mkdir foo && rm -f foo
rm: cannot remove 'foo': Is a directory
````
I tried running ct-ng with a .config directory in the current dir:
- First, kconfig moves it away as `.config.old` when it creates a new configuration
- `ct-ng distclean` then complains:
````
  CLEAN scripts
  CLEAN log
  CLEAN build dir
  CLEAN .config
rm: cannot remove '.config.old': Is a directory
ct-ng:172: recipe for target 'distclean' failed
make: *** [distclean] Error 1
````
Besides, I don't see how your proposed solution of removing `.config.*` from that command line would change anything for you since your issue was removal of `.config` - which would still be removed by  your proposed command.

**Comment by stilor** [comment]
In other words, your `.config` may still be present as `.config.old`.

That said, I think it is well documented that crosstool-NG and kconfig work with a file named .config in the current directory, e.g. here: http://crosstool-ng.github.io/docs/configuration/

I may add a check that `.config`, if present, is a regular file - and err out of ct-ng otherwise. But this seems more of a user error that a bug in crosstool-NG.

**Comment by howey** [comment]
Thank you for the quick response.

You're right in that `rm -f .config` would not remove `.config` if it happened to be a directory. In my testing, I made a directory called `.foo`, and then tried `rm -f ..foo`, as I wasn't sure what the second dot at the beginning of the path would do. I remember not getting the "Is a directory message" and not seeing the `.foo` directory after I had run the command, however now I realize that in my testing I probably ran `ls`, and not `ls -al`, which would have caused the `.foo` directory to be hidden from my view at the time. The -f flag would have muted any message that the file did not exist prior to running the command. This led me to believe that the extra dot at the beginning did something unexpected and caused my directory to be deleted, however I now believe that I simply messed up during my test.

I'll check tomorrow to see if my `~/.config` has been moved to `~/.config.old`. I suspect it will be, provided that ct-ng does no do anything to remove any file or directory called `config.old`. Then I could just move my `~/.config.old` to `~/.config`. That would be acceptable, although in my opinion this behavior is still unexpected.
