### ISSUE TITLE
When using ct-ng RESTART, environment variables restored by state env.sh are not exported

### ISSUE THREAD

**Issue by nyetwurk** [crosstool-ng/crosstool-ng#762]
As of fae66ae34fb6fcade87abb3aa48bcdbf5fead662

First found when I was trying to fix ltrace (pull request #760) - CONFIG_SHELL was not properly exported, so ./configure for ltrace was failing (it was using /bin/sh to interpret libtool)

When generating env.sh, should each variable set be prepended with "export"?

**Comment by nyetwurk** [comment]
Adding "export -p" in script functions thusly:
```
    # Restore the environment, discarding any error message
    # (for example, read-only bash internals)
    CT_DoLog STATE "  Restoring environment from ${state_dir}/env.sh"
    . "${state_dir}/env.sh" >/dev/null 2>&1 || true
    export -p
```
clearly shows that CONFIG_SHELL is not exported, even though it exists in env.sh

It is my understanding that bash is supposed to mark every variable set via "." or "source" as exported. I am not sure why it is not in this instance. Perhaps a bash bug? Or some other bash setting?

**Comment by nyetwurk** [comment]
```
export eval `cat "${state_dir}/env.sh"`
```
rather than
```
. "${state_dir}/env.sh"
```
seems to solve the problem

**Comment by stilor** [comment]
Thanks for tracking it down! Indeed, CT_DoLoadState does not export any variable it loads - it just source the env.sh. Sourcing does not export anything implicitly, it just executes the commands in the sourced file.

Probably, we need to save the type of the variable (local/exported) when saving the environment. Something along the lines of replacing `set` in `CT_DoSaveState` with `{ set; export -p; }` (it will print exported variables twice, but since the 2nd time it is setting  to the same variable, it should not be a problem.

**Comment by stilor** [comment]
Your solution probably goes too far - it exports everything, even the variable that were not exported at the time the state was saved. Ideally, we should be restoring the variables in the same state as they were.

**Comment by stilor** [comment]
Ideally, we should also only record the stuff we set in the environment. Otherwise, we end up restoring a lot of bogus variables such as `SSH_CLIENT` - the job may have been restarted in a different SSH session. We should save the environment at the very beginning and only save/load the differences. But I guess this is an enhancement for another day.

**Comment by nyetwurk** [comment]
More than that, it has lots of problems with quotes.. eval does some bad bad things.

In the meantime, I suggest keeping at least a little of my ltrace PR.. or even just hardcoding "export CONFIG_SHELL" in functions?

**Comment by nyetwurk** [comment]
BTW agreed on {set; export -p} side effects.
