### ISSUE TITLE
Configuration arm-unknown-linux-androidhf not supported Makefile:4062: recipe for target 'configure-gcc' failed

### ISSUE THREAD

**Issue by crocki89** [crosstool-ng/crosstool-ng#772]
### Crosstool-NG version:
crosstool-ng-1.23.0-90
### Host OS and its version
Ubuntu 16.04. Kernel: Linux 4.4.0-34-generic
### Attach `.config`
http://paste.ubuntu.com/25038278/
### Attach `build.log` 
tail -n 200: http://paste.ubuntu.com/25038275/
Full: https://yadi.sk/i/7mgl6kOL3KqFo7
Full direct: https://docviewer.yandex.ru/view/520881363/?*=n4jD1CFITUdBHEwAl3CYRf3y5AV7InVybCI6InlhLWRpc2stcHVibGljOi8vbWFWTkVZaVN1THpZa2t6Ty8vNUJELzFHa0o5YTVmeWd0S1BSU3llSnJkND0iLCJ0aXRsZSI6ImJ1aWxkLmxvZyIsInVpZCI6IjUyMDg4MTM2MyIsInl1IjoiNDkwNzc0MjYzMTQ5OTQyMDg3NyIsIm5vaWZyYW1lIjpmYWxzZSwidHMiOjE0OTk0MjEwNTM3NTB9

**Comment by stilor** [comment]
There are two problems here.

First, there's indeed a bug in crosstool-NG - android for 32-bit ARM should be configured as "arm-...-androideabi". This also uncovered that 64-bit ARM (AArch64) sample names are misnamed; the eabi suffix does not apply to AArch64. For this, I'll post a PR shortly.

But even with that fix, a hard-float configuration does not build due to incompatible CRT objects provided by android-ndk distribution: the crtbegin_so.o in the archive is using incompatible soft-float ABI. One could probably build a custom android-ndk with hard-float ABI, but crosstool-NG currently does not support rebuilding bionic from sources.
