### ISSUE TITLE
bootstrap fails on MacOS Sierra

### ISSUE THREAD

**Issue by alfishe** [crosstool-ng/crosstool-ng#797]
crosstool-NG version - master HEAD bcaec4d80a1099a1039520cae47f11957809e217
Host OS: MacOS 10.12.6 (Sierra latest)

bootstrap fails immediately after execution, not producing configure file. Execution log attached.

[bootstrap.zip](https://github.com/crosstool-ng/crosstool-ng/files/1216479/bootstrap.zip)

MacPro_5:~ dev$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by alfishe** [comment]
declare -A / local -A not supported in MacOS. Need to be replaced to declare -a / local -a.

But there are other errors related to incorrect id generation:
1) ./bootstrap: line 439: @{pkg_name}-@{version}-linux-x86_64: syntax error: operand expected (error token is "@{pkg_name}-@{version}-linux-x86_64")
2) ./bootstrap: line 650: Target Architecture: syntax error in expression (error token is "Architecture")

**Comment by alfishe** [comment]
Seems bootstrap is created on machine with Bash4 - developing on worst machine with obsolete packages - that might result with better code quality and compatibility =)

**Comment by stilor** [comment]
`declare -a` and `declare -A` are not the same. One declares a normal array, the other is for associative arrays (hashes)

Well, this is really macOS problem, not ct-ngs :) bash 3.2 is 10 (sic!) years old; this should've been more than enough time to update to bash4. As far as I understand, you can update your bash via homebrew.

But I do think it makes sense to start a practice of posting snapshots (with tarballs already containing files that are normally generated by `bootstrap`). I'll leave this open as a feature request, but it is not of a very high priority.

**Comment by alfishe** [comment]
Seems the only way to get toolchain working on Mac - get 1.23 release, turn on obsolete packages support (with gettext-0.17). That was the only combination that works. Any other attempts failed miserably.

**Comment by stilor** [comment]
Nobody promised you that *unreleased* versions are going to work everywhere, especially on a proprietary OS that is a royal pain to set up in a VM. Because of that, I am not testing every change on macOS - only as a part of the release cycle.

But if you prefer, I can officially declare macOS unsupported until there is an active maintainer with a keen interest in macOS.

**Comment by EE-GSlomin** [comment]
While I'm sure that nobody actually wants MacOS to move to an unsupported position, it may actually help. There are quite a few projects out there which rely on crosstool and claim that they are supported on Mac OS. This usually results in someone banging their head against a wall for a week before giving up.

At least if crosstool (officially) did not support OSX some of these vendors might be a little more pressed into actually adding said support.

**Comment by stilor** [comment]
Current state is that I test MacOS in a VM as a part of a release cycle. Which means `master` may be broken on MacOS, but it may so be on FreeBSD/ArchLinux/anything that I don't run on my development machine.

So if one wants to track the "bleeding edge" of development, `master`, on a host other than Ubuntu - be my guest and submit PRs/issues as soon as things break on your OS of choice. Otherwise, the list of OSes mentioned in the docs gets tested before the release.

That said, I plan to start 1.24 cycle in a month or so.
