### ISSUE TITLE
restore blackfin support

### ISSUE THREAD

**Issue by malachib** [crosstool-ng/crosstool-ng#848]
I know it's in the TODO already, but I'd like to officially request blackfin support back again

**Comment by WolleTD** [comment]
I'm wondering what's the issue with blackfin? I have some old BF537 processors and naively threw stuff into crosstool-ng until it built a cross-compiler for me: https://github.com/WolleTD/crosstool-ng/commit/357af675297bbbc49fc741f13f20ca2d6ba764ac

After sorting out stuff, this worked with a GCC 11.2, uclibc-ng 1.0.39, binutils 2.37 and Kernel headers 2.6.32. I only have systems that can run statically linked bFLT binaries built with `-Wl,-elf2flt` and not looked into QEMU yet, but some (old C) applications appear to work.

I have a Catch2-Test-Suite that's completely failing though. There were some patch-files removed in the [PR removing blackfin support](https://github.com/crosstool-ng/crosstool-ng/pull/244), but it seems I have to keep digging for information about the actual issues this architecture has.

**Comment by cpackham** [comment]
The main problem for blackfin is the lack of any sign of support for the architecture landing in the various upstream components that crosstool-ng uses.  Even ADI seem to have lost interest in it https://ez.analog.com/dsp/software-and-development-tools/linux-blackfin/f/q-a/108907/end-of-life-for-blackfin-linux

**Comment by WolleTD** [comment]
That's true and unfortunate. As the last ADI toolchain release is a GCC 4.3 though – but in 2014 – I keep wondering if it's possible to build some newer version that fully supports C++11. Guess I'll get on with my archaeological work.

Trying to build GCC 4.9 with my changes fatally fails with a segmentation fault in the compiler. I have the feeling that's because the host runs GCC 11 and that's unable to build the old 4.9 sources, but haven't tried with another target yet.

**Comment by cpackham** [comment]
I'm closing this as there seems little chance of support for blackfin appearing in upstream gcc/glibc/linux.

**Comment by malachib** [comment]
Frankly, this seems quite sensible.
