### ISSUE TITLE
Build fails on final gcc compiler for RPi 3 target (macOS)

### ISSUE THREAD

**Issue by masterjefferson** [crosstool-ng/crosstool-ng#859]
**Environment**
- crosstool-NG version: `1.23.0`
- Host OS: `macOS High Sierra 10.13.2 Beta (17C60c)`
- Xcode Command Line Tools: `9.0`

My config is based on the `armv8-rpi3-linux-gnueabihf` sample with minimal modifications (paths mainly). I had to switch to `gettext v0.19.7` or that would fail as well.

`.config` and `build.log` are in the attached zip file.

[files.zip](https://github.com/crosstool-ng/crosstool-ng/files/1456178/files.zip)

**Comment by masterjefferson** [comment]
Using `ulimit -n 1024` fixes the issue on the `cc_for_host` step.

Now it is failing when compiling gdb (`debug` step):

`/Volumes/CT_NG/.ct-ng-build/src/gdb-7.12.1/gdb/doublest.c:258:19: error: use of undeclared identifier 'min'; did you mean 'fmin'?`

**Comment by stilor** [comment]
Can you try GDB8 with recent `master`? You'll need bash from homebrew to run bootstrap.

This seems like the issue described here https://trac.macports.org/ticket/55035, but before I dig into this I'd like to see if it has already been fixed upstream.

**Comment by masterjefferson** [comment]
Yes, `master` works! Thanks.

**Comment by stilor** [comment]
Ok, thanks for confirming. I'll reopen the issue - I need to find the change that fixed it and backport it to 7.12.

**Comment by fluber** [comment]
crosstool-NG version: 1.23.0
Host OS: macOS Sierra 10.12.6（16G1036）
Xcode Command Line Tools: Xcode 9.1
GNU gdb (GDB) 8.0.1

my config is base on armv7-rpi2-linux-gnueabihf. 

I have reinstalled the GDB 8.0.1, still got the same error.

[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/1471120/config.zip)


[log.zip](https://github.com/crosstool-ng/crosstool-ng/files/1471108/log.zip)

**Comment by stilor** [comment]
I didn't talk about host GDB, rather, GDB that crosstool-NG builds.

**Comment by fluber** [comment]
the previous error, I used the brew install crosstool-ng to build.

this successful case, I installed the crosstool-ng from git. 

cross-NG version: crosstool-ng-1.23.0-247-g0b1595ac-dirty
Host OS: macOS Sierra 10.12.6（16G1036）
Xcode Command Line Tools: Xcode 9.1
Bash Version: 4.4.12(1)-release
tarballs gdb version: gdb-8.0.1

my config is base on armv7-rpi2-linux-gnueabihf.

I have successfully built, didn't get the error.

**Comment by audiofanatic** [comment]
@fluber When using the crosstool-NG 1.23.0 release (i.e. not from brew and not using crosstool-NG from git), you can get past the gdb error by turning on experimental features and providing your own custom gdb. Download the 8.0.1 release tarball from the official gdb site and point your `.config` at it. The crosstool-NG build then completes successfully (for me using armv8-rpi3-linux-gnueabihf, but I would expect your rpi2 case to be similar). Don't know if this would work for crosstool-NG coming from brew, I had other problems with the brew version so switched to the official crosstool-NG release and had a much smoother run (just the gdb issue and the other [known issue with gettext](770#issuecomment-315550970), which was easy to resolve once the problem was identified).

**Comment by capraynor** [comment]
How to change the GDB version to GDB8? Cannot find that in menuconfig.
Just replace the source code in  `.build/src/gdb-7.12.1` ? or do something else?
Thanks!

**Comment by stilor** [comment]
`master` has GDB 8.x, so it should be a moot issue now
