### ISSUE TITLE
Build failed in step 'Extracting and patching toolchain components'

### ISSUE THREAD

**Issue by rypz79** [crosstool-ng/crosstool-ng#860]
crosstool-NG v1.23
host OS: Ubuntu 17.10 (x86_64-pc-linux-gnu)
target OS: QEMO (arm-unknown-linux-gnueabi)
`
[INFO ]  Extracting and patching toolchain components
[WARN ]    Sources for libelf-0.8.13 were partially extracted/patched, cleaning up
[EXTRA]    Extracting libelf-0.8.13
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Extracting and patching toolchain components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: CT_Extract[scripts/functions@1803]
[ERROR]  >>        called from: CT_DoExtractPatch[scripts/functions@1871]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@1698]
[ERROR]  >>        called from: CT_ExtractPatch[scripts/functions@1994]
[ERROR]  >>        called from: do_libelf_extract[scripts/build/companion_libs/200-libelf.sh@16]
[ERROR]  >>        called from: do_companion_libs_extract[scripts/build/companion_libs.sh@22]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@627]
`
Patching functions as instructed [here](https://github.com/crosstool-ng/crosstool-ng/pull/791/files) didn't solve the problem
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/1463658/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1463659/config.txt)

**Comment by stilor** [comment]
First, when reporting the version, please report exactly what `ct-ng version` tells you. These changes were not in the 1.23 release.

This should be fixed in `master`; the problem with libelf's hosting webserver is that it doesn't return an error if a non-existent file is requested. So, please:
- update to most recent `master`
- remove any stale libelf tarballs you may have
- retry

And if it still fails, please indicate the exact version you're using.

**Comment by stilor** [comment]
timed out
