### ISSUE TITLE
AVR Fail: configure: error: cannot compute suffix of object files: cannot compile

### ISSUE THREAD

**Issue by 8ohmh** [crosstool-ng/crosstool-ng#879]
Another problem:
Same environmen like in post 
`https://github.com/crosstool-ng/crosstool-ng/issues/878`
```
[ERROR]    checking for suffix of object files... configure: error: in `/ssd/000-abricks/work_dir/.build/avr/build/build-cc-gcc-final/avr/libgcc':
[ERROR]    configure: error: cannot compute suffix of object files: cannot compile
```
[avr_failed_02.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/1532388/avr_failed_02.tar.gz)

c286005dccd06425468e99bb267de473  avr-failed/avr_failed_02.tar.gz

**Comment by stilor** [comment]
If you looked into the config.log in build-gcc/final/avr/libgcc (where it fails), you'd see:
````
xgcc: error: unrecognized command line option '-mcpu=avr'
````
Why did you add this option? This shouldn't have been very hard: start with known-good sample configurations and add your changes (if you need them) one step at a time. If it breaks, then probably you did something wrong. Take a step back, read the docs (e.g. GCC manual, especially the options for the target you're configuring the toolchain for), think again and try in a different way.

E.g. https://gcc.gnu.org/onlinedocs/gcc/AVR-Options.html lists possible inputs to `-mcpu`; what you supplied is not a valid option. Moreover, on targets that may need CPU specification, ct-ng offers a menu option to enter the desired value. It doesn't do that on AVR for a reason: avr-libc and newlib both build for all possible CPU variants (which is why "multilib" option is always selected on AVR).

I am not here to do your homework for you, sorry.
