### ISSUE TITLE
Unknown stat format options causes failure at start of build

### ISSUE THREAD

**Issue by m-fonseca** [crosstool-ng/crosstool-ng#890]
- is crosstool-NG version crosstool-ng-1.23.0-288-gadaa3a5d
- cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- [build.log](https://github.com/crosstool-ng/crosstool-ng/files/1593627/build.log)
- [config.log](https://github.com/crosstool-ng/crosstool-ng/files/1593628/config.log)

`mkdir ct-ng-test`
`cd ct-ng-test`
`ct-ng arm-cortex_a8-linux-gnueabi`
...
`ct-ng build`                      
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20171229.125250
[INFO ]  Building environment variables
[ERROR]  Unknown stat format options
...

`stat --version`
stat (GNU coreutils) 8.28

**Comment by Chrisys93** [comment]
I have the same problem, trying to build a toolchain for cross-compiling for RPi 3.
I used [this link](https://elinux.org/RPi_Linaro_GCC_Compilation) for the configuration of the toolchain beforehand and also posted on [here](https://github.com/pfalcon/esp-open-sdk/issues/137) about it, but did not get a response yet.
It's in a way good to see that there are more people who have a similar issue.
Hope we can get some advice soon.

**Comment by stilor** [comment]
That's strange since your build.log shows GNU version of stat has been successfully detected:
````
[DEBUG]    CT_CONFIGURE_has_stat_flavor_GNU=y
````
The code that uses this option (and outputs this error message) is:
````
        case "${CT_CONFIGURE_has_stat_flavor_GNU},${CT_CONFIGURE_has_stat_flavor_BSD}" in
            y,*)
                mode="$(stat -c '%a' "$(dirname "${dir}")")"
                ;;
            *,y)
                mode="$(stat -f '%Lp' "$(dirname "${dir}")")"
                ;;
            *)
                CT_Abort "Unknown stat format options"
                ;;
        esac
````
This is in scripts/functions file. I don't see how this case statement may not get into the first option if the `CT_CONFIGURE_has_stat_flavor_GNU` is set to `y`. As you could suspect, it works for me on multiple Linux distros that I tried it (Ubuntu, CentOS, ArchLinux, Gentoo) and worked some time ago on MacOS too - and this code hasn't changed since.

Do you have any weird bash options set that affect pattern matching behavior?

Other than that, you can insert a debugging print above this `case` statement to check that the values of these variables retain the previously dumped values:
````
CT_DoLog DEBUG "[${CT_CONFIGURE_has_stat_flavor_GNU},${CT_CONFIGURE_has_stat_flavor_BSD}]"
````
Then retry `ct-ng build` and attach the new build.log.

**Comment by stilor** [comment]
Cannot reproduce and no response from OP.
