### ISSUE TITLE
INFORMATION needed.

### ISSUE THREAD

**Issue by Zibri** [crosstool-ng/crosstool-ng#921]
on an embedded system I have this libc:
```
# /lib/libc.so.6 
GNU C Library (crosstool-NG 1.20.0 - 4.8-2016.03-x86_64) stable release version 2.19, by Roland McGrath et al.
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.3 20140401 (prerelease).
Compiled on a Linux 3.16.0 system on 2016-03-09.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

How can I create a toolchain like the one used?

**Comment by stilor** [comment]
Ideally, by installing the same version of crosstool-NG and selecting the same versions of all components. This is not really doable, though, as the download URLs keep changing, build machine's environment keep changing and crosstool-NG has since had a lot of fixes since 1.20 - I wouldn't expect 1.20 to work out of the box now.

That said, you should be able to select close enough version in the current crosstool-NG master (e.g. GCC 4.8.5 instead of 4.8.3, Linux 3.16.x instead of 3.16.0, etc). This printout does not tell you the version of the binutils to select, so you may need to play a bit to see which one compiles - glibc depends pretty heavily on specific features in binutils.

This should produce a toolchain, which won't be exactly the same, but should be compatible with your target glibc.
