### ISSUE TITLE
Dual ABI error when linking code against GeographicLib

### ISSUE THREAD

**Issue by JacekRuzyczka** [crosstool-ng/crosstool-ng#930]
When building my C++ app for the Raspberry Pi 3B using `arm-unknown-linux-gnueabi-g++ (crosstool-NG 1.21.0) 5.1.0` on my 64-bit PC running openSuSE Leap 42.2, I'm always running into a strange error when trying to link the compiled code against the GeographicLib library:

`main.o: In function 'OnDisplayGPSTimerElapsed()':
/import/valen/autoradio/main.cpp:251: undefined reference to 'GeographicLib::DMS::Encode[abi:cxx11](double, GeographicLib::DMS::component, unsigned int, GeographicLib::DMS::flag, char)'
/import/valen/autoradio/main.cpp:260: undefined reference to 'GeographicLib::DMS::Encode[abi:cxx11](double, GeographicLib::DMS::component, unsigned int, GeographicLib::DMS::flag, char)'
collect2: error: ld returned 1 exit status
`
After looking into this, I found out this could be a _dual ABI_ issue, but as I'm using a pre-built GeographicLib, I can't modify it. This, BTW, is the code snippet of my app, which usees the lib:

`output << DMS::Encode (gps_data.fix.latitude, DMS::SECOND, 2, DMS::LATITUDE) << endl;
output << DMS::Encode (gps_data.fix.longitude, DMS::SECOND, 2, DMS::LONGITUDE) << endl;`

Compiling and linking on the Pi by using g++ 4.9.2 does not make such trouble. Any idea that's going on here? Thank you.

**Comment by stilor** [comment]
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

"If you get linker errors about undefined references to symbols that involve types in the std::__cxx11 namespace or the tag [abi:cxx11] then it probably indicates that you are trying to link together object files that were compiled with different values for the _GLIBCXX_USE_CXX11_ABI macro. This commonly happens when linking to a third-party library that was compiled with an older version of GCC. If the third-party library cannot be rebuilt with the new ABI then you will need to recompile your code with the old ABI. "

Did you tried the proposed solution in that article (defining `_GLIBCXX_USE_CXX11_ABI` to 0 before including any headers)?

**Comment by JacekRuzyczka** [comment]
The problem is that I'm using C++11 throughout my project. Setting the macro to 0 generates errors in another corner (namely the database driver). So I'll have to rebuild GeographicLib using C++11, right?

**Comment by stilor** [comment]
First, I don't think crosstool-NG can help you with this problem: this is squarely within GCC's ABI, so you should talk to them about ways to solve it. For some reason, this macro is settable individually for each compilation unit, so it may be possible somehow to have wrappers around GeographicLib's interfaces. But again, this is something you should bring up on GCC's mailing lists.

I'd appreciate if you leave a reference to email thread or to the suggested solution here, as a guidance to other users.

**Comment by JacekRuzyczka** [comment]
OK, I've just asked the guys who wrote the GeographicLib for help: https://sourceforge.net/p/geographiclib/discussion/1026621/thread/c5a409c0/
